### ISSUE TITLE
Can't set tags as input to deploy from terraform

### ISSUE THREAD

**Issue by rlabinot** [vmware/terraform-provider-vra#216]
**vRA version**
The vRA on-premise / 8.1 version with cumulative patch 1
**Terraform version**
The terraform version 0.12.19
**terraform-provider-vra plugin version**
The terraform-provider-vra plugin version 0.2.2

**Describe the bug**
Can't set tags as input of a deployment from terraform. Only string type is allowed for inputs.

Here is a sample of the tags the blueprint to deploy :
```
formatVersion: 1
inputs:
  tags:
    type: array
    title: Tags
    description: Tags to apply to machines
    items:
      type: object
      properties:
        key:
          type: string
          title: Key
        value:
          type: string
          title: Value
resources:
  Cloud_vSphere_Machine_1:
    type: Cloud.vSphere.Machine
    properties:
      image: '${input.image}'
      flavor: '${input.flavor}'
      networks:
        - network: '${resource.Cloud_vSphere_Network_1.id}'
      tags: '${input.tags}'
```

**This is the part of my inputs in terraform :** 
```
  inputs = {
    "image": "myLinux",
    "flavor": "Small",
    "tags": [
      {"key": "test1","value": "test1"},
      {"key": "test2","value": "test2"},
      {"key": "test3","value": "test3"}
    ]
 }
```

**Here is a view of the error logs :**

```
$ terraform.exe apply

Error: Incorrect attribute value type

  on main.tf line 26, in resource "vra_deployment" "this":
  26:   inputs = {
  27:     "image": "LRA_SLES15_CloudInit",
  28:     "flavor": "Small",
  29:     "tags": [
  30:       {"key": "test1","value": "test1"},
  31:       {"key": "test2","value": "test2"},
  32:       {"key": "test3","value": "test3"}
  33:     ]
  34:   }

Inappropriate value for attribute "inputs": element "tags": string required.
```

**Tried with a "string as array" like this :** 
`"tags": "[{'key': 'test1','value': 'test1'},{'key': 'test2','value': 'test2'},{'key': 'test3','value': 'test3'}]"`

**But error asking array by the way :** 
```
Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vra_deployment.this: Creating...

Error: [POST /catalog/api/items/{id}/request][400] requestCatalogItemUsingPOSTBadRequest  &{Message:tags: Expected type ARRAY but was STRING. StatusCode:400}

  on main.tf line 16, in resource "vra_deployment" "this":
  16: resource "vra_deployment" "this" {
```

Strange that it asks a string, then if you give a string, it asks an array ?

**To Reproduce**

Take the same files as the example : https://github.com/vmware/terraform-provider-vra/tree/master/examples/deployment/catalog_item
Rename terraform.tfvars.sample to terraform.tfvars and add the variables
Terraform plan to see the error

**Expected behavior**
Deploy the blueprint with given tags as terraform inputs.

**Desktop (please complete the following information):**

OS: Windows
