### ISSUE TITLE
vRA Use existing networks & network profiles

### ISSUE THREAD

**Issue by chrisd27519** [vmware/terraform-provider-vra#75]
The documentation, i.e. syntax examples, to properly identify networks on machine resources and to use vRA constraint tags to select the correct network profile is non-existent. We have been unable to work through the proper terraform yaml to select a network profile and attach a machine to the existing network.

**Comment by dmettem** [comment]
@chrisd27519 Terraform vRA provider uses IaaS api for machine resource which by design requires the individual network id to which the machine is to be attached. The [machine](https://github.com/vmware/terraform-provider-vra/blob/master/examples/machine/main.tf) example here shows how this can be achieved. However the `vra_network` data source requires the exact name, not the constraints.
I think I understood the requirement a bit, but it would help if you can provide more details. Thanks!

**Comment by tenthirtyam** [comment]
Example....

**main.tf**
```
// VERSIONS

terraform {
  required_providers {
    vra = {
      source  = "vmware/vra"
      version = ">= 0.3.3"
    }
  }
  required_version = ">= 0.15"
}

// PROVIDERS

provider "vra" {
  url           = var.vra_url
  refresh_token = var.vra_api_token
  insecure      = var.vra_insecure
}

// DATA

data "vra_cloud_account_vsphere" "this" {
  name = var.cloud_account_vsphere
}

data "vra_cloud_account_nsxt" "this" {
  name = var.cloud_account_nsxt
}

data "vra_region" "this" {
  cloud_account_id = data.vra_cloud_account_vsphere.this.id
  region           = var.region
}

data "vra_fabric_network" "this" {
  for_each = var.network_ip_ranges
  filter   = "name eq '${each.value.subnet_name}' and cloudAccountId eq '${data.vra_cloud_account_nsxt.this.id}'"
}

// RESOURCES

// Add network profile using the IP ranges defined in the plan.

resource "vra_network_profile" "this" {
  name               = var.name
  description        = var.description
  region_id          = data.vra_region.this.id
  fabric_network_ids = [for i in data.vra_fabric_network.this : i.id]
  isolation_type     = var.isolation_type
}

// Add network IP ranges for internal (non-IPAM) IP address management.

resource "vra_network_ip_range" "this" {
  for_each          = var.network_ip_ranges
  fabric_network_id = data.vra_fabric_network.this[each.key].id
  name              = each.value["ip_range_name"]
  description       = each.value["ip_range_description"]
  start_ip_address  = each.value["start_ip_address"]
  end_ip_address    = each.value["end_ip_address"]
  ip_version        = each.value["ip_version"]
  tags {
    key   = "function"
    value = each.value["tag_function"]
  }
  tags {
    key   = "env"
    value = each.value["tag_environment"]
  }
}
```

**variables.tf**

```
// Endpoints

variable "vra_url" {
  type        = string
  description = ""
  default     = "https://cloud.rainpole.io"
}

variable "vra_api_token" {
  type        = string
  description = ""
}

variable "vra_insecure" {
  type        = bool
  description = ""
  default     = false
}

# Cloud Assembly

variable "cloud_account_nsxt" {
  type        = string
  description = "The name of the NSX-T cloud account. (e.g sfo-w01-nsx01)"
}

variable "cloud_account_vsphere" {
  type        = string
  description = "The name of the vCenter Server cloud account. (e.g sfo-w01-vc01)"
}

variable "region" {
  type        = string
  description = "The region for the network profile"
}

variable "name" {
  type        = string
  description = "A name for the network profile"
}

variable "description" {
  type        = string
  description = "A description for the network profile."
}

variable "isolation_type" {
  type        = string
  description = "The network isolation type. (e.g. NONE)"
}

variable "network_ip_ranges" {
  type = map(object({
    subnet_name          = string
    ip_range_name        = string
    ip_range_description = string
    start_ip_address     = string
    end_ip_address       = string
    ip_version           = string
    tag_function         = string
    tag_environment      = string
  }))
  description = "A mapping of objects for network IP ranges associated with a network profile."
}
```

**terraform.tfvars**

```
// ENDPOINTS

vra_url       = "https://cloud.rainpole.io"
vra_api_token = "******************************"
vra_insecure  = false

// NETWORK PROFILE - EXISTING

// Network Profiles

cloud_account_nsxt    = "sfo-w01-nsx01"
cloud_account_vsphere = "sfo-w01-vc01"
region                = "Datacenter:datacenter-3"
name                  = "net-existing-sfo-w01-vc01-01"
description           = "Existing Networks - Workload Domain 01"
isolation_type        = "NONE"
network_ip_ranges = {
  ip_range0 = {
    subnet_name          = "sfo-prod-web-172-11-10-0–24"
    ip_range_name        = "172-11-10-0–24"
    ip_range_description = "Production Web Tier Network"
    start_ip_address     = "172.11.10.10"
    end_ip_address       = "172.11.10.254"
    ip_version           = "IPv4"
    tag_function         = "web"
    tag_environment      = "prod"
  }
  ip_range1 = {
    subnet_name          = "sfo-prod-db-172-11-11-0–24"
    ip_range_name        = "172-11-11-0–24"
    ip_range_description = "Production Database Tier Network"
    start_ip_address     = "172.11.11.10"
    end_ip_address       = "172.11.11.254"
    ip_version           = "IPv4"
    tag_function         = "db"
    tag_environment      = "prod"
  }
  ip_range2 = {
    subnet_name          = "sfo-prod-app-172-11-12-0–24"
    ip_range_name        = "172-11-12-0–24"
    ip_range_description = "Production Application Tier Network"
    start_ip_address     = "172.11.12.10"
    end_ip_address       = "172.11.12.254"
    ip_version           = "IPv4"
    tag_function         = "app"
    tag_environment      = "prod"
  }
  ip_range3 = {
    subnet_name          = "sfo-dev-web-172-12-10-0–24"
    ip_range_name        = "172-12-10-0–24"
    ip_range_description = "Development Web Tier Network"
    start_ip_address     = "172.12.10.10"
    end_ip_address       = "172.12.10.254"
    ip_version           = "IPv4"
    tag_function         = "web"
    tag_environment      = "dev"
  }
  ip_range4 = {
    subnet_name          = "sfo-dev-db-172-12-11-0–24"
    ip_range_name        = "172-12-11-0–24"
    ip_range_description = "Development Database Tier Network"
    start_ip_address     = "172.12.11.10"
    end_ip_address       = "172.12.11.254"
    ip_version           = "IPv4"
    tag_function         = "db"
    tag_environment      = "dev"
  }
  ip_range5 = {
    subnet_name          = "sfo-dev-app-172-12-12-0–24"
    ip_range_name        = "172-12-12-0–24"
    ip_range_description = "Development Application Tier Network"
    start_ip_address     = "172.12.12.10"
    end_ip_address       = "172.12.12.254"
    ip_version           = "IPv4"
    tag_function         = "app"
    tag_environment      = "dev"
  }
}
```

Then in the vloud template YAML you can use constraint tags on the network like so....

```
....snipttet.....
inputs:
  targetCloud:
    type: string
    oneOf:
      - title: Rainpole Private Cloud
        const: 'cloud:private'
    title: Cloud
    description: Select a cloud platform.
  targetRegion:
    type: string
    oneOf:
      - title: San Francisco (US West 1)
        const: 'region:us-west-1'
      - title: Los Angeles (US West 2)
        const: 'region:us-west-2'
    title: Region
    description: Select a region.
  targetEnvironment:
    type: string
    oneOf:
      - title: Production
        const: 'env:prod'
      - title: Development
        const: 'env:dev'
    title: Environment
    description: Select a target environment.
  targetFunction:
    type: string
    oneOf:
      - title: Web Server
        const: 'function:web'
      - title: Application Server
        const: 'function:app'
      - title: Database Server
        const: 'function:db'
    title: Function
    description: Select a function.
....snipttet.....
  Cloud_NSX_Network_1:
    type: Cloud.NSX.Network
    properties:
      networkType: existing
      constraints:
        - tag: '${input.targetFunction}'
        - tag: '${input.targetEnvironment}'
....snipttet.....
```
